---
version: 2
jobs:
  python:
    parallelism: 1
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install yamllint
          command: |
            sudo pip install yamllint
      - run:
          name: run yamllint
          command: ./script/test/yamllint.sh
  node:
    parallelism: 1
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: get test dependency
          command: npm install
      - run:
          name: run eslint
          command: ./script/test/eslint.sh

workflows:
  version: 2
  all:
    jobs:
      - python
      - node
